server:
  port: 8191
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/birudeogarande/spring-cloud-config
          #username: birudeogarande@gmail.com
          #password: !Qazwsxc
          search-paths:
          - '*service'
          